import { Mail, MapPin, MessageCircle, Navigation, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/PageHero";
import { SEO, breadcrumbSchema, webPageSchema } from "@/components/SEO";
import { COMPANY, MAPS_DIRECTIONS, MAPS_EMBED, WHATSAPP_DEFAULT } from "@/data/company";

export default function ContactPage() {
  return <>
    <SEO title="Contato | Schultz Energia Solar em Linhares" description="Fale com a Schultz Energia Solar em Linhares-ES. WhatsApp, e-mail, endereço comercial e mapa para atendimento em energia fotovoltaica." path="/contato/" schema={[webPageSchema("Contato | Schultz Energia Solar em Linhares", "/contato/"), breadcrumbSchema([{ name: "Início", path: "/" }, { name: "Contato", path: "/contato/" }])]} />
    <PageHero eyebrow="Atendimento local" title="Fale com a Schultz Energia Solar" description="Envie sua conta de luz para uma análise inicial ou venha conversar com a nossa equipe em Linhares." breadcrumbs={[{ label: "Contato" }]} primaryLabel="Falar pelo WhatsApp" />
    <section className="section-padding bg-background"><div className="container-max mx-auto grid lg:grid-cols-[0.75fr_1.25fr] gap-10"><div><h2 className="font-display text-3xl font-bold text-secondary mb-6">Informações de contato</h2><address className="not-italic space-y-4"><div className="border border-border p-5 rounded-lg flex gap-4"><MapPin className="h-6 w-6 text-primary shrink-0" /><div><p className="font-bold text-secondary">Schultz Energia Solar</p><p className="text-muted-foreground mt-1">{COMPANY.address.street}<br />{COMPANY.address.district}<br />{COMPANY.address.city}-{COMPANY.address.state}<br />CEP {COMPANY.address.zip}</p></div></div><a href={`tel:${COMPANY.phoneE164}`} className="border border-border p-5 rounded-lg flex gap-4 hover:border-primary"><Phone className="h-6 w-6 text-primary" /><div><p className="font-bold text-secondary">WhatsApp e telefone</p><p className="text-muted-foreground">{COMPANY.phoneDisplay}</p></div></a><a href={`mailto:${COMPANY.email}`} className="border border-border p-5 rounded-lg flex gap-4 hover:border-primary"><Mail className="h-6 w-6 text-primary" /><div><p className="font-bold text-secondary">E-mail</p><p className="text-muted-foreground break-all">{COMPANY.email}</p></div></a></address><div className="grid sm:grid-cols-2 gap-3 mt-6"><Button size="lg" asChild><a href={WHATSAPP_DEFAULT} target="_blank" rel="noopener noreferrer">Falar pelo WhatsApp<MessageCircle /></a></Button><Button variant="outline" size="lg" asChild><a href={MAPS_DIRECTIONS} target="_blank" rel="noopener noreferrer">Como chegar<Navigation /></a></Button></div></div><div><div className="aspect-[4/3] lg:aspect-auto lg:h-full min-h-[420px] border border-border overflow-hidden rounded-lg"><iframe src={MAPS_EMBED} title="Mapa da Schultz Energia Solar em Linhares" className="w-full h-full" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></div></section>
  </>;
}