import { ArrowRight, Building2, Factory, Home, Tractor, Wrench } from "lucide-react";
import { Link } from "react-router-dom";
import { solutions, services } from "@/data/pages";

const icons = [Home, Building2, Tractor, Factory];

export function ServicesSection() {
  return <>
    <section id="solucoes" className="section-padding bg-background"><div className="container-max mx-auto"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-10"><div className="max-w-3xl"><p className="text-primary uppercase font-bold text-sm mb-3">Soluções por segmento</p><h2 className="font-display text-3xl md:text-5xl font-bold text-secondary">Um projeto para cada tipo de consumo</h2></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">{solutions.map((item, index) => { const Icon = icons[index]; return <Link to={item.path} key={item.path} className="group border border-border p-6 rounded-lg hover:border-primary hover:shadow-medium transition-all"><Icon className="h-8 w-8 text-primary mb-6" /><h3 className="font-display text-xl font-bold text-secondary mb-3">{item.navLabel}</h3><p className="text-sm text-muted-foreground mb-6 line-clamp-3">{item.intro}</p><span className="inline-flex items-center gap-2 text-primary font-bold text-sm">Conhecer solução<ArrowRight className="h-4 w-4" /></span></Link>; })}</div></div></section>
    <section id="servicos" className="section-padding bg-secondary text-secondary-foreground"><div className="container-max mx-auto"><div className="max-w-3xl mb-10"><p className="text-primary uppercase font-bold text-sm mb-3">Serviços especializados</p><h2 className="font-display text-3xl md:text-5xl font-bold mb-5">Cuidado completo durante toda a vida do sistema</h2><p className="text-lg text-secondary-foreground/65">Da instalação ao diagnóstico de falhas, nossa equipe mantém seu sistema gerando como deveria.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{services.map(item => <Link key={item.path} to={item.path} className="group p-5 border border-secondary-foreground/15 rounded-lg hover:border-primary bg-secondary-foreground/5"><Wrench className="h-6 w-6 text-primary mb-4" /><h3 className="font-display text-lg font-bold mb-2">{item.navLabel}</h3><p className="text-sm text-secondary-foreground/60 line-clamp-2 mb-4">{item.metaDescription}</p><span className="inline-flex items-center gap-2 text-primary font-bold text-sm">Saiba mais<ArrowRight className="h-4 w-4" /></span></Link>)}</div></div></section>
  </>;
}
